# Generated by Django 4.1.1 on 2022-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='db_image',
            field=models.FileField(max_length=250, null=True, upload_to='db_img/'),
        ),
    ]
