# Generated by Django 4.1.1 on 2022-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_db_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='db_image',
            field=models.ImageField(blank=True, null=True, upload_to='db_image/'),
        ),
    ]
